version: '3.8'

services:
  web:
    build: .
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./app-data:/app/instance
      - ./init_db.sh:/app/init_db.sh
    networks:
      - dechets-network
      - traefik_traefik
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=0
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@db:5432/waste_registry
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik_traefik'
      
      # Middleware pour la redirection HTTP vers HTTPS
      - 'traefik.http.middlewares.redirection.redirectScheme.scheme=https'
      - 'traefik.http.middlewares.redirection.redirectScheme.permanent=true'
      
      # Configuration du service
      - 'traefik.http.services.dechets_tls.loadbalancer.server.port=8000'

      # Routeur pour le trafic HTTP (redirigé vers HTTPS)
      - 'traefik.http.routers.dechets_http.rule=Host(`${DOMAIN}`)'
      - 'traefik.http.routers.dechets_http.entrypoints=http'
      - 'traefik.http.routers.dechets_http.middlewares=redirection'
      
      # Routeur pour le trafic HTTPS
      - 'traefik.http.routers.dechets_tls.rule=Host(`${DOMAIN}`)'
      - 'traefik.http.routers.dechets_tls.entrypoints=https'
      - 'traefik.http.routers.dechets_tls.tls.certresolver=webssl'
      - 'traefik.http.routers.dechets_tls.tls=true'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=waste_registry
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - dechets-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  app-data:
  db-data:

networks:
  dechets-network:
    driver: bridge
  traefik_traefik:  
    external: true